name: Deploy React + Vite (GitHub / Vercel)

on:
  workflow_dispatch:
    inputs:
      deploy_github:
        description: 'Deploy no GitHub Pages (true/false)'
        required: true
        default: 'false'
      deploy_vercel:
        description: 'Deploy na Vercel (true/false)'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy no GitHub Pages
        if: ${{ inputs.deploy_github == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy na Vercel
        if: ${{ inputs.deploy_vercel == 'true' }}
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}